version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    container_name: frontend
    networks:
      - cilltan
    depends_on:
      - db-endpoints-server
      - create-join-group-server
      # - mongo_one
  
  db-endpoints-server:
    build:
      context: ./backend/db-endpoints-server
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    container_name: db-endpoints-server
    networks:
      - cilltan
    # depends_on:
    #   - mongo_one

  create-join-group-server:
    build:
      context: ./backend/create-join-group-server
      dockerfile: Dockerfile
    image: create-join-group-server:latest
    container_name: create-join-group-server
    env_file:
      - ./backend/create-join-group-server/.env
    networks:
      - cilltan
    ports:
      - 8080:5000
  
  user-signupin-server:
    build: 
      context: ./backend/user-signupin-server
      dockerfile: Dockerfile
    ports:
      - 7777:5000
    container_name: user-signupin-server
    networks:
      - cilltan
  
  event-search:
    build:
      context: backend/event-search
      dockerfile: Dockerfile
    image: event-search:latest
    container_name: event-search
    networks:
      - cilltan
    ports:
      - 5001:5000

  prometheus:
    build:
      context: backend/monitor/prometheus
      dockerfile: Dockerfile
    image: prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      # - backend/monitor/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./backend/monitor/prometheus/prometheus_data:/prometheus
    networks:
      - cilltan
    ports:
      - 9090:9090

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    restart: unless-stopped
    networks:
      - cilltan
    ports:
      - 9100:9100

  grafana:
    build:
      context: backend/monitor/grafana
      dockerfile: Dockerfile
    image: grafana:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    depends_on:
      - prometheus
      - node-exporter
    networks:
      - cilltan
    ports:
      - "3030:3000"

networks:
  cilltan:
    driver: bridge

  # mongo_one:
  #   image: mongo
  #   container_name: mongodb
  #   ports:
  #     - 27017:27017
  #   networks:
  #     - cilltan
  #   restart: always
    # env_file:
    #   - ./backend/mongo/mongo-variables.env
    # command: mongod --replSet mongo-set      
    # volumes:
    #   - ./backend/mongo/data/mongo-1:/data/db

  # mongo_two:
  #   image: mongo
  #   container_name: mongo2
  #   ports:
  #     - 30002:27017
  #   networks:
  #     - cilltan
  #   restart: always
  #   command: mongod --replSet mongo-set
  #   volumes:
  #     - ./backend/mongo/data/mongo-2:/data/db

  # mongo_three:
  #   image: mongo
  #   container_name: mongo3
  #   ports:
  #     - 30003:27017
  #   networks:
  #     - cilltan
  #   restart: always
  #   command: mongod --replSet mongo-set
  #   volumes:
  #     - ./backend/mongo/data/mongo-3:/data/db

  # mongo_creater:
  #   image: mongo
  #   container_name: mongo_creater
  #   entrypoint: ["mongosh","--host","mongo1","--port","27017","--eval", 'rs.initiate( { _id : "mongo-set",members: [{ _id: 0, host: "mongo1:27017" },{ _id: 1, host: "mongo2:27017" },{ _id: 2, host: "mongo3:27017" }   ]})']
  #   depends_on:
  #     - mongo_one
  #     - mongo_two
  #     - mongo_three

  # mongo-express:
  #   image: mongo-express
  #   container_name: mongo-express
  #   # env_file:
  #   #   - ./backend/mongo/mongo-express-variables.env
  #   environment:
  #     - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017/
  #   restart: always
  #   depends_on:
  #     - mongo_one
  #   ports:
  #     - 8081:8081
  #   networks:
  #     - cilltan