version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    container_name: frontend
    networks:
      - cilltan
    depends_on:
      - db-endpoints-server
      - create-join-group-server
      - mongo
      - user-signupin-server
  
  db-endpoints-server:
    build:
      context: ./backend/db-endpoints-server
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    container_name: db-endpoints-server
    networks:
      - cilltan
    depends_on:
      - mongo

  create-join-group-server:
    build:
      context: ./backend/create-join-group-server
      dockerfile: Dockerfile
    image: create-join-group-server:latest
    container_name: create-join-group-server
    # environment:
    #   - ATLAS_URI=${ATLAS_URI}
    env_file:
      - ./backend/create-join-group-server/.env
    networks:
      - cilltan
    ports:
      - 8080:5000

  mongo:
    image: mongo
    container_name: mongodb
    env_file:
      - ./backend/mongo/mongo-variables.env
    ports:
      - 27017:27017
    networks:
      - cilltan
    volumes:
      - ./backend/mongo/mongo-data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    env_file:
      - ./backend/mongo/mongo-express-variables.env
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    networks:
      - cilltan

  user-signupin-server:
    build: 
      context: ./backend/user-signupin-server
      dockerfile: Dockerfile
    env_file:
      - ./backend/user-signupin-server/.env
    # environment:
    #   - ATLAS_URI=${ATLAS_URI}
    ports:
      - 7777:5000
    container_name: user-signupin-server

networks:
  cilltan:
    driver: bridge