global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "access-log"
    metrics_path: /activities/metrics
    scrape_interval: 3s
    static_configs:
      - targets: ["db-endpoints-server:5000"]
    # dns_sd_configs:
    #   - names:
    #       - db-endpoints-server
    #     type: A
    #     port: 5000
        
  - job_name: "docker"
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:9323"]
