name: Branch-microservice-checking
on:
  push:
    branches:
      - 'user-signupin'
env:
  ATLAS_URI : ${{ secrets.ATLASURI  }}
jobs:
  Check_Docker_compose:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/user-signupin'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: user-signupin
        
      - name: Build and run Docker Compose
        run: |
          docker-compose up -d
          
      - name: Set up environments
        run: |
          python3 -m pip install --upgrade pip
          if [ -e requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run tests 
        run: |
          # Run your tests against the running Docker Compose services
          # python3 -m unittest test.py -b -v
          curl -X POST -H "Content-Type: application/json" -d '{"email": "value12", "password": "value2"}' http://localhost:7777/signup

      - name: Clean up
        run: docker-compose down