name: Branch-microservice-checking
on:
  push:
    branches:
      - 'user-signupin'
env:
  ATLAS_URI : ${{ secrets.ATLASURI  }}
jobs:
  Check_Docker_compose:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/user-signupin'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: user-signupin
        
      - name: Build and run Docker Compose
        run: |
          docker-compose up -d

      - name: Run tests 
        run: |
          # Run your tests against the running Docker Compose services
          cd backend
          cd user-signupin-server
          python3 -m unittest test.py -b -v

      - name: Clean up
        run: docker-compose down
