name: Docker-Compose and Dockerfile Check
on:
  push:
    branches:
      - main
env:
  ATLAS_URI : ${{ secrets.ATLASURI  }}
jobs:
  Check_Docker_compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Docker Compose Action
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: docker-compose.yml
  
      - name: Build and run Docker Compose
        run: |
          docker swarm init
          docker compose build
          docker stack deploy --compose-file docker-stack.yml chilltan

      - name: Run tests with Docker Compose
        run: |
          # Run your tests against the running Docker Compose services

      - name: Clean up
        run: docker stack rm chilltan

